sudo: false

language: php
matrix:
  include:
  - php: 5.3
    dist: precise
  allow_failures:
  - php: 5.3

services:
  - mysql

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master

php:
  - 5.6
  - 7.1
  - 7.2
  - 7.3

cache:
  - composer
  - $HOME/.composer/cache

env:
  global:
    - WP_CLI_BIN_DIR=/tmp/wp-cli-phar

before_script:
  - bash bin/install-package-tests.sh

script: ./vendor/bin/behat
